# Generated by Django 2.1.15 on 2024-03-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Meat', 'Meat'), ('Dessert', 'Dessert'), ('Vegetable', 'Vegetable'), ('Sauces', 'Sauces')], max_length=20, null=True),
        ),
    ]
