# Generated by Django 2.1.15 on 2024-04-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_dashboard', '0002_auto_20240309_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expirydate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Meat', 'Meat'), ('Dessert', 'Dessert'), ('Vegetable', 'Vegetable'), ('Sauces', 'Sauces'), ('Fruit', 'Fruit')], max_length=20, null=True),
        ),
    ]
