# Generated by Django 2.1.15 on 2024-04-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_dashboard', '0004_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_quantity',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('Meat', 'Meat'), ('Dessert', 'Dessert'), ('Vegetable', 'Vegetable'), ('Sauces', 'Sauces'), ('Fruit', 'Fruit')], max_length=20, null=True),
        ),
    ]
